import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Brand Identity
        noir:  '#0E0E0E',
        ivory: '#F9F9F9',
        gold:  '#C9A96E',
        mink:  '#8C7B6B',
        // Material Design Surface Tokens (from prototype)
        'surface-container':         '#eeeeee',
        'surface-container-low':     '#f3f3f4',
        'surface-container-high':    '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'surface-container-lowest':  '#ffffff',
        'surface-bright':            '#f9f9f9',
        'surface-dim':               '#dadada',
        'surface-variant':           '#e2e2e2',
        'surface-tint':              '#5f5e5e',
        'on-surface':                '#1a1c1c',
        'on-surface-variant':        '#444748',
        'on-background':             '#1a1c1c',
        background:                  '#f9f9f9',
        surface:                     '#f9f9f9',
        outline:                     '#747878',
        'outline-variant':           '#c4c7c7',
        primary:                     '#000000',
        'on-primary':                '#ffffff',
        'primary-container':         '#1c1b1b',
        'on-primary-container':      '#858383',
        secondary:                   '#6b5c4d',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#f1dcc9',
        'on-secondary-container':    '#6f6051',
        tertiary:                    '#000000',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#261900',
        'on-tertiary-container':     '#9c8049',
        error:                       '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'inverse-surface':           '#2f3131',
        'inverse-on-surface':        '#f0f1f1',
        'inverse-primary':           '#c9c6c5',
        // Status colors
        success:  '#2d6a4f',
        warning:  '#b5838d',
        info:     '#457b9d',
      },
      fontFamily: {
        cormorant: ['"Cormorant Garamond"', 'serif'],
        garamond:  ['"EB Garamond"', 'serif'],
        raleway:   ['Raleway', 'sans-serif'],
        // Aliases matching prototype
        'headline-lg':        ['"EB Garamond"', 'serif'],
        'headline-md':        ['"EB Garamond"', 'serif'],
        'display-lg':         ['"EB Garamond"', 'serif'],
        'display-md':         ['"EB Garamond"', 'serif'],
        'body-lg':            ['Raleway', 'sans-serif'],
        'body-md':            ['Raleway', 'sans-serif'],
        'label-caps':         ['Raleway', 'sans-serif'],
        button:               ['Raleway', 'sans-serif'],
      },
      fontSize: {
        'display-lg':         ['80px',  { lineHeight: '96px',  letterSpacing: '-0.02em', fontWeight: '300' }],
        'display-md':         ['64px',  { lineHeight: '72px',  letterSpacing: '-0.01em', fontWeight: '300' }],
        'headline-lg':        ['48px',  { lineHeight: '56px',  fontWeight: '300' }],
        'headline-lg-mobile': ['32px',  { lineHeight: '40px',  fontWeight: '300' }],
        'headline-md':        ['32px',  { lineHeight: '40px',  fontWeight: '300' }],
        'body-lg':            ['18px',  { lineHeight: '32px',  letterSpacing: '0.01em',  fontWeight: '400' }],
        'body-md':            ['16px',  { lineHeight: '28px',  fontWeight: '400' }],
        'label-caps':         ['12px',  { lineHeight: '16px',  letterSpacing: '0.15em',  fontWeight: '600' }],
        button:               ['14px',  { lineHeight: '20px',  letterSpacing: '0.1em',   fontWeight: '500' }],
      },
      spacing: {
        'section-gap':      '120px',
        'section-gap-sm':   '80px',
        'margin-mobile':    '20px',
        'margin-tablet':    '40px',
        'margin-desktop':   '80px',
        gutter:             '32px',
        'container-max':    '1440px',
        18:  '72px',
        22:  '88px',
        26:  '104px',
        30:  '120px',
        34:  '136px',
        38:  '152px',
        42:  '168px',
        46:  '184px',
        50:  '200px',
        54:  '216px',
        58:  '232px',
        62:  '248px',
        66:  '264px',
        70:  '280px',
        74:  '296px',
        78:  '312px',
        82:  '328px',
        86:  '344px',
        90:  '360px',
        94:  '376px',
        98:  '392px',
        102: '408px',
        106: '424px',
        110: '440px',
        120: '480px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      transitionTimingFunction: {
        luxury: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      transitionDuration: {
        400: '400ms',
        600: '600ms',
        700: '700ms',
        800: '800ms',
        900: '900ms',
        1000: '1000ms',
        1200: '1200ms',
      },
      animation: {
        'fade-in':       'fadeIn 0.6s ease-out forwards',
        'fade-up':       'fadeUp 0.7s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-in-left': 'slideInLeft 0.5s cubic-bezier(0.16,1,0.3,1) forwards',
        'slide-in-right':'slideInRight 0.5s cubic-bezier(0.16,1,0.3,1) forwards',
        shimmer:         'shimmer 1.5s infinite',
        bounce:          'bounce 2s infinite',
        'spin-slow':     'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          from: { opacity: '0', transform: 'translateX(-24px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(24px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        shimmer: {
          '0%':   { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      aspectRatio: {
        '3/4':   '3 / 4',
        '4/5':   '4 / 5',
        '2/3':   '2 / 3',
        '5/6':   '5 / 6',
      },
      gridTemplateColumns: {
        'admin-layout': '220px 1fr',
      },
      zIndex: {
        60: '60',
        70: '70',
        80: '80',
        90: '90',
        100: '100',
      },
    },
  },
  plugins: [],
}

export default config
